---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nfs-exporter-py
  namespace: nfs-exporter
  labels:
    app.kubernetes.io/name: nfs-exporter-py
data:
  config.yaml: |
    dir_path: /home/elghali,/home/elghali/myFiles
    port: 9469
    metric_freq: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-exporter-py
  namespace: nfs-exporter
  labels:
    app.kubernetes.io/name: nfs-exporter-py
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nfs-exporter-py
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nfs-exporter-py
    spec:
      containers:
        - name: nfs-exporter-py
          image: elghali/nfs_exporter_py:1.4
          ports:
            - name: http
              containerPort: 9469
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9469
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9469
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /nfs_exporter_py/config.yaml
              subPath: config.yaml
            - mountPath: /ni
              name: nfs-root
      volumes:
        - name: config
          configMap:
            name: nfs-exporter-py
            defaultMode: 0777
        - name: nfs-root
          nfs:
            path: <mountPath>
            server: <nfsIp>