---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-exporter-py
  namespace: script-exporter
  labels:
    app.kubernetes.io/name: script-exporter-py
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: script-exporter-py
  template:
    metadata:
      labels:
        app.kubernetes.io/name: script-exporter-py
    spec:
      containers:
        - name: script-exporter-py
          image: elghali/script_exporter_py:1.0
          env:
          - name: dir_path
            value: /ni/path_to_dir
          ports:
            - name: http
              containerPort: 9469
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9469
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9469
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /ni
              name: ni-etl-root
      volumes:
        - name: ni-etl-root
          nfs:
            path: /script-exporter/ni
            server: 10.0.1.12
            
